### ISSUE TITLE
Property "centerWidth" was accessed during render but is not defined on instance.

### ISSUE THREAD

**Issue by shuTwT** [haixin-fang/vue-form-design#13]
packages/editor/layouts
/Framework.vue 中centerWidth不知为何在setup中没有return，使用时控制台弹出警告
![image](https://github.com/haixin-fang/vue-form-design/assets/95295076/eeaca2a2-fc40-4792-9a57-34af54db4110)

**Comment by haixin-fang** [comment]
@shuTwT  感谢大佬提供建议  问题已修复
