### ISSUE TITLE
项目打包报错怎么办

### ISSUE THREAD

**Issue by yyx680** [haixin-fang/vue-form-design#5]
![image](https://github.com/haixin-fang/vue-form-design/assets/48463629/955ee88c-b384-4f85-831a-9cc753c2546a)

**Comment by haixin-fang** [comment]
@yyx680 不是这个命令 需要参考package.json文件中的script字段, 其中的key就是我们要执行的命令行, 这个时候就会获取node_modules中的vite包去执行 ,而直接执行vite build的话, 除非全局安装过vite, 不然会执行失败, 如果不想全局安装, 也可以安装npx包, 通过npx vite build 来执行当前文件夹下node_modules中的任何包都行

如果有其他问题可以继续提issue
