### ISSUE TITLE
希望增加导出json使用例子

### ISSUE THREAD

**Issue by lihuacai168** [haixin-fang/vue-form-design#7]
看到issuse有一个类似的问题，我也有这个疑惑。  
导出来的json，不知道如何使用。
希望可以增加一个完整的代码例子，非常感谢

**Comment by haixin-fang** [comment]
@lihuacai168 
https://github.com/haixin-fang/vue-form-design/blob/master/playground/src/components/Form.vue

你好, 这里就是使用的例子, starfish-form组件就是json的渲染器

README.md里面有相应说明

`formResult`可以为空,list 是通过编辑器生成的json,搭配使用

```js
<Dynamicform v-model:formResult="formResult" :allFormList="list" ></Dynamicform>
```

如果还有疑问可以提issue
