### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by Yolo-00** [haixin-fang/vue-form-design#8]
![image](https://github.com/haixin-fang/vue-form-design/assets/129492349/4c69f05c-57fa-4688-be0a-cfb7543b10e9)

自定义配置模板 通过提供的**setJson**方法设置编辑器后点击保存无效，需要先选中控件后才可保存

**Comment by haixin-fang** [comment]
@Yolo-00 自定义模版 保存的时候判断表单无改动给return了 

已修复 看看可以了吗

**Comment by Yolo-00** [comment]
不行，保存回调没有执行

**Comment by haixin-fang** [comment]
<img width="563" alt="企业微信截图_ced036df-410e-4fb0-8487-0be023c5dfb0" src="https://github.com/haixin-fang/vue-form-design/assets/48665972/5cd392b0-a261-4400-8cd2-3a676de614aa">
@Yolo-00 我看执行了 要不你调试排查看看

**Comment by Yolo-00** [comment]
"version": "1.1.18",
`
[
    {
        "ControlType": "Selected",
        "nameCn": "选择器",
        "id": "w4W4kdKNfeon1zp3rHPbk",
        "layout": false,
        "data": {
            "fieldName": "structure",
            "label": "电箱结构",
            "tip": "",
            "placeholder": "请选择电箱结构",
            "showRule": "{}",
            "required": true,
            "rule": "[]",
            "itemConfig": {
                "value": "",
                "items": [
                    {
                        "label": "一体式",
                        "value": "Y",
                        "select": false,
                        "id": 1
                    },
                    {
                        "label": "分体式",
                        "value": "F",
                        "select": false,
                        "id": 2
                    },
                    {
                        "label": "其他类型",
                        "value": "Q",
                        "select": false,
                        "id": 3
                    }
                ],
                "id": ""
            },
            "csslist": []
        }
    },
    {
        "ControlType": "Selected",
        "nameCn": "选择器",
        "id": "6ho85NPNrPQ0PQSxzKTSj",
        "layout": false,
        "data": {
            "fieldName": "coldStorage",
            "label": "冷库类型",
            "tip": "",
            "placeholder": "请选择冷库类型",
            "showRule": "{}",
            "required": true,
            "rule": "[]",
            "itemConfig": {
                "value": "",
                "items": [
                    {
                        "label": "医用冷库",
                        "value": "Y",
                        "select": false,
                        "id": 1
                    },
                    {
                        "label": "常规冷库",
                        "value": "C",
                        "select": false,
                        "id": 2
                    },
                    {
                        "label": "其他类型",
                        "value": "Q",
                        "select": false,
                        "id": 3
                    }
                ],
                "id": ""
            }
        }
    },
    {
        "ControlType": "Selected",
        "nameCn": "选择器",
        "id": "DhNx9iDzSTiPmBcRblyEW",
        "layout": false,
        "data": {
            "fieldName": "productionUnit",
            "label": "生产机组（台）",
            "tip": "",
            "placeholder": "请选择生产机组",
            "showRule": [
                [
                    {
                        "field": "coldStorage",
                        "logic": "=",
                        "type": "选项",
                        "value": "Y"
                    }
                ]
            ],
            "required": true,
            "rule": "[]",
            "itemConfig": {
                "value": "",
                "items": [
                    {
                        "label": "1",
                        "value": "1",
                        "select": false,
                        "id": 1
                    },
                    {
                        "label": "2",
                        "value": "2",
                        "select": false,
                        "id": 2
                    }
                ],
                "id": ""
            }
        }
    },
    {
        "ControlType": "Text",
        "nameCn": "文本框",
        "id": "Sd8QZrr3EQ5E4Kf5Qn7-W",
        "layout": false,
        "data": {
            "fieldName": "unitPower",
            "label": "机组功率(HP)",
            "tip": "",
            "placeholder": "请输入机组功率",
            "showRule": [
                [
                    {
                        "field": "structure",
                        "logic": "!=",
                        "type": "选项",
                        "value": "Y"
                    }
                ]
            ],
            "required": true,
            "rule": [],
            "default": ""
        }
    }
]
`

// template
`
<starfish-editor ref="editorRef" @save="handleSave" :panel="['form', 'json']"
            :basic-fields="['Text', 'Selected']" :layout-fields="['']" :headerShow="false"
            :menu="{ left: ['delete', 'undo', 'tree', 'save', 'preview', 'fullscreen'], right: [''], column: false }"
            class="starfish-editor">
        </starfish-editor>
`

// js
`
const editorRef = ref();
const handleSave = (e) => {
    console.log(e, "====");
};

> 

onMounted(() => {
    editorRef.value.setJson(initConfig);
});
`

**Comment by Yolo-00** [comment]
我这边排查了，确实是没有执行 **@save**

**Comment by haixin-fang** [comment]
@Yolo-00 再试试 

https://github.com/haixin-fang/vue-form-design/commit/f12822788f720e684b8591c06f7199c9edf2acb7

**Comment by Yolo-00** [comment]
好像还是不太行

**Comment by haixin-fang** [comment]
<img width="1349" alt="企业微信截图_d114ec34-01b8-4386-a282-8f473e188fe7" src="https://github.com/haixin-fang/vue-form-design/assets/48665972/12577f23-165d-495e-bb1b-76e28b26b201">
@Yolo-00  我用你发的案例调试 没问题

**Comment by Yolo-00** [comment]
[dome.zip](https://github.com/haixin-fang/vue-form-design/files/14718191/dome.zip)

**Comment by Yolo-00** [comment]
![image](https://github.com/haixin-fang/vue-form-design/assets/129492349/0192580f-7d5d-4310-89a2-3aa14f0ab3bc)

先点击设置按钮后点击保存是没有反应
需要先选中控件后点击保存回调才能成功执行

**Comment by haixin-fang** [comment]
@Yolo-00 未打包就发布1.1.19了 重新发布了新版本1.1.20

**Comment by Yolo-00** [comment]
可以了
